### ISSUE TITLE
Customize (Theme Color) Example

### ISSUE THREAD

**Issue by donPuerto** [BayBreezy/ui-thing#10]
Hi do we have component for this? Customize

![image](https://github.com/BayBreezy/ui-thing/assets/9329005/2586a830-b568-4ce9-9cbc-031e4fac6fde)

By the way mate nice work

**Comment by BayBreezy** [comment]
Hey @donPuerto , I did not bother adding ti as it is available on shadcn/ui and shadcn-vue.
What I did add was the ability to switch your theme from the cli. So if you run `npx ui-thing@latest theme`, you can switch to any of the themes that you see on their website.

If you don't want to use the CLI, then you can just make your selections on shadcn/ui and then copy it and paste it into your nuxt app with ui-thing, it will work 😄

**Comment by donPuerto** [comment]
Thanks mate.. Wonderful work

**Comment by BayBreezy** [comment]
Thanks. I appreciate it
