### ISSUE TITLE
Two-faced description?

### ISSUE THREAD

**Issue by LauraWebdev** [BayBreezy/ui-thing#11]
I've noticed something when checking out this project for the first time. On the frontpage, it is written that this project was made because `I also wanted to learn how to build a component library.`.

Right afterwards, a line below, it is stated that `This is NOT a component library.`.

Not a big deal, just thought it was odd to read.

**Comment by BayBreezy** [comment]
Hey @LauraWebdev , Thanks for catching this.
I initially wanted to do a component lib... but then the projects transformed into the nuxt version of shadcn/ui.
I will update this because really and truly, its a port of shadcn/ui.
