### ISSUE TITLE
Documentation broken

### ISSUE THREAD

**Issue by dpschen** [BayBreezy/ui-thing#13]
When I open [the documentation](https://ui-thing.behonbaker.com/getting-started/introduction) I get this error:

![image](https://github.com/user-attachments/assets/7ba0d1ea-0ce2-4153-ab69-dfa6c758e95f)

**Comment by BayBreezy** [comment]
Yeah. Thanks for reporting it. I created an issue on the nuxt repo. Hoping to get some help soon. You can see it here: https://github.com/nuxt/nuxt/issues/28127

**Comment by BayBreezy** [comment]
@dpschen So I got the build to work by adding `shiki` to the list of dependencies that should be transpiled.

```ts
build: { transpile: ["vue-sonner", "shiki"] },
```

I doubt this is the correct way to get this to work. It was never an issue in the past but maybe something changed in the shiki repo that i am not aware of. 

Waiting to see if the nuxt team has a better solution. But the deployment seems to be working for now.
