### ISSUE TITLE
[Feature request] Mention component

### ISSUE THREAD

**Issue by Satont** [BayBreezy/ui-thing#14]
Hello! Do you implementing feature requests? If yes I'd appreciate to see something similar to https://www.naiveui.com/en-US/os-theme/components/mention (https://codesandbox.io/s/rfn2nx)

My scenario of usage:

1. If mention was triggered by `:` symbol, then show one list of items.
2. If mention was triggered by `@` symbol, then show another list of items.
3. It should support textarea.
4. It should support customizable render of list item.
5. It should optionally support virtual list render? In case there is to much items.

If that's already possible in any way, i'll appreciate any help.

**Comment by BayBreezy** [comment]
Hey @Satont This looks like a nice component. Most of the components in this repo come from Radix Vue, so I would probably have to make a feature request on their repo for something like this and then style it and add it to the list of components here.

**Comment by BayBreezy** [comment]
Hey @Satont ,

It would seem that the current version of Radix-Vue stops this from becoming a thing. Based on what happened here: https://github.com/unovue/radix-vue/issues/1384

I was checking around to see if a component exists for vue 3 that could provide this functionality but I was out of luck.

**Comment by Satont** [comment]
@BayBreezy thank you for your answser.
