### ISSUE TITLE
Error nuxt-icon dependency not found.

### ISSUE THREAD

**Issue by davidreyg** [BayBreezy/ui-thing#16]
This package has been renamed to @nuxt/icon [here!](https://github.com/nuxt/icon/pull/175)

I actually made a PR [here!](https://github.com/leamsigc/ui-thing-cli/pull/1) that fix it. 😁👌

**Comment by BayBreezy** [comment]
Hey @davidreyg ,
Thanks. I have been meaning to do this. I keep forgetting. I will merge it soon

**Comment by BayBreezy** [comment]
close with this https://github.com/BayBreezy/ui-thing-cli/releases/tag/v0.1.24
