### ISSUE TITLE
Layout Blocks

### ISSUE THREAD

**Issue by justindefodji** [BayBreezy/ui-thing#17]
Hello,

Thank you for your work.

Is it possible to build some layouts blocks in block section quick responsive layout pickup.
I can make a PR but I have no net yet!

**Comment by BayBreezy** [comment]
Hey @justindefodji ,

I don't think I understand the request. The blocks section is just some code snippets that you can use to create a page or add to a section of your page. 

You want an entire page to be in the example?

**Comment by justindefodji** [comment]
Thank you for your reply @BayBreezy,

I was referring to dashboard layouts, not an entire page.

**Comment by BayBreezy** [comment]
Oh... Ok got it.
Dashboard layouts will be added soon.
What I did was just put the different blocks that can make a dashboard there. But I will put it together soon.

**Comment by justindefodji** [comment]
NIce! 

Thank you @BayBreezy
