### ISSUE TITLE
Dialog close button offset

### ISSUE THREAD

**Issue by BlueBazze** [BayBreezy/ui-thing#23]
![image](https://github.com/user-attachments/assets/23357516-e92c-43ac-b939-982207220f21)

From what i see, both the y position and height is off.
In `Ui/Dialog/Content.vue` the usage of UiDialogClose has a class for `top-2` which differs from shadcn-vue that has `top-4`.
Is this a typo or by intention?

The height of the button. I believe it is because the nuxt icon renders as a `<span>` which causes line-height to kick in which is 24px.
Adding the prop `mode="svg"` to the icon fixes this.

Here is a screenshot of the changes.
![image](https://github.com/user-attachments/assets/1f78d4ae-132e-4278-83d0-df3eaf9a051d)

Now the button is square and placed the same distance from the top and right.
![image](https://github.com/user-attachments/assets/8303f4e4-431b-495f-aeda-d2ca433c85e9)

Im not gonna make a pr for this since the changes are so small, and the fact that i dont know if the top was intentionally set to 2.

**Comment by BayBreezy** [comment]
Hello!
Ehhhhh... I mean... I can make the change... The good thing is that you own the code, so you can update it. Thanks for pointing it out tho. 
I honestly cant say it it was a mistake or  done intentionally, I don't remember lol

**Comment by BayBreezy** [comment]
Done 🙂
