### ISSUE TITLE
Is there a license, such as MIT?

### ISSUE THREAD

**Issue by gregmsanderson** [BayBreezy/ui-thing#3]
Hello,

I came across your repo after looking at shadcn-vue. Both look great!

However I noticed there was no `LICENSE.md`, for example:

https://github.com/radix-vue/shadcn-vue/blob/dev/LICENSE

If these components can be used by anyone, would you consider adding one?

Thanks.

**Comment by BayBreezy** [comment]
Hey @gregmsanderson , I did not realize that the license was not added lol

This is free! You can take it and do whatever(just not bad stuff).

Just give it a star is all i ask lololol. I will go ahead and add the MIT to it.

**Comment by gregmsanderson** [comment]
No problem, that's great. It's worth doing since it'll then show up in more searches for e.g MIT.

I've already given it a star! :)

**Comment by BayBreezy** [comment]
Thank you! 
I appreciate it. I just added the license with the star requirement lol.. 
All the stuff used was given to me for free.. Its only right that I give it back for free
