### ISSUE TITLE
【Function request】New layout block demonstration

### ISSUE THREAD

**Issue by ecfxs** [BayBreezy/ui-thing#32]
Hello, thank you for your outstanding work
I would like to inquire if a similar layout can be introduced
I'm not very good at animation. I hope there are blocks like this.

https://www.shadcn-vue.com/docs/components/sidebar.html

**Comment by BayBreezy** [comment]
@ecfxs Check out the updated docs. I got a chance to add the sidebar https://ui-thing.behonbaker.com/blocks/sidebar

**Comment by ecfxs** [comment]
> @ecfxs查看更新后的文档。我有机会添加侧边栏https://ui-thing.behonbaker.com/blocks/sidebar

Thank you very much for your excellent work! I would recommend my friends around me to use it
