### ISSUE TITLE
[DOCS] Show badge for updated components on sidebar

### ISSUE THREAD

**Issue by therealokoro** [BayBreezy/ui-thing#39]
Hi Breezy,

First of all. I want to appreciate your effort in making these. I have been able to make my own starter template from these. I've been following this since its launch.

I just wanted to suggest that you show a `Updated` badge for components you have done a major improvement on in the docs, so we don't miss it. Just like you have the `New` badge for new components.

I would have missed the new cool stuffs you added to the `button` component if I hadn't checked it again.

Thanks

**Comment by BayBreezy** [comment]
Hey @therealokoro 

Thank you! Happy to hear that you were able to use it and do something great 🚀

I do add the badges 🤣

I had the `Updated` badge next to the buttons for a while. So what I tend to do is just add the badge and then remove it after a week OR when I make another major update on another component.

I may need to start a changelog page. That way you can just go there and see what changed and when.

**Comment by therealokoro** [comment]
I guess it's really been a while since I visited the docs 😂.

Well then, the changelog page would be a good idea.

Thank you once again for your good work. Looking forward to collaboration
in future 😊

**Comment by BayBreezy** [comment]
Hey @therealokoro ,

I added the changelog page. Thanks for the suggestion.

I didnt go all the way back BUT I will ensure that all updates are added there moving forward.
