### ISSUE TITLE
Installing Ui Thing resulted in dark class being applied to root html

### ISSUE THREAD

**Issue by AliD201** [BayBreezy/ui-thing#4]
Hello, 
Hope you are doing well. 

I have been trying out Ui-things and noticed the following 

Installing Ui Thing resulted in dark class being applied to root html and thus will set the page default to dark. 

How to revert that ? i tried setting up `color-mode` in the `nuxt.config.ts` to `light/system` but still the same issue.  

Note that it is not changing the color mode

Update: modifying it inside the page does change it, but my issue is with the default.  

Any clue on how to fix that ?

**Comment by BayBreezy** [comment]
Hey @AliD201,

The color mode module will use the value stored in local storage to determine if it should add the dark class to the html element in the DOM. 
Can you check what the value of `nuxt-color-mode` is in localstorage?

If you delete the property from localstorage & refresh the page, color mode should use the system's light/dark mode value.

**Comment by BayBreezy** [comment]
@AliD201 , did you get this resolved?

**Comment by AliD201** [comment]
Sorry for the late reply, had a lot going on. 

And yes i noticed that after deleting the key and refreshing it works with the setted up preference mode. 

Maybe my local storage was sit to dark from another project and since they are both local and same port, things transferred ?

**Comment by BayBreezy** [comment]
Yes. That is exactly what happened.

I always have to remove that key when hopping between different projects.

Glad you got it resolved 👍🏽
