### ISSUE TITLE
Error initializing project with ui-thing on fresh Nuxt 3 app using Yarn

### ISSUE THREAD

**Issue by mtzrmzia** [BayBreezy/ui-thing#46]
I encountered an issue when initializing a fresh Nuxt 3 app using `npx ui-thing@latest init`. The process fails due to an error involving the `@nuxtjs/tailwindcss` module and unmet peer dependencies. I am using **Yarn** as the package manager.

### Steps to Reproduce

	1.	Create a fresh Nuxt 3 app:

`npx nuxi@latest init nuxt-app`

	2.	Select Yarn as the package manager during the setup process.
	3.	Run the following command to initialize the ui-thing setup:

`npx ui-thing@latest init`

	4.	Observe the error.

### Expected Behavior

The initialization process should complete successfully, installing all necessary dependencies and setting up the project.

### Actual Behavior

The initialization fails with the following error:

ERROR  Nuxt module should be a function: @nuxtjs/tailwindcss

Additional warnings and unmet peer dependencies are also reported:
	•	"nuxt > @nuxt/devtools@1.6.3" has unmet peer dependency "vite@*".
	•	"nuxt > nitropack > openapi-typescript@7.4.4" has unmet peer dependency "typescript@^5.x".
	•	" > tailwind-variants@0.3.0" has unmet peer dependency "tailwindcss@*".

### Environment

	•	Nuxt Version: 3.14.1592
	•	Node Version: 20.12.2
	•	Package Manager: Yarn 1.22.22
	•	Command Used: npx ui-thing@latest init

### Error Logs

ERROR  Nuxt module should be a function: @nuxtjs/tailwindcss

  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2466:11)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  ...

### What I Tried

	•	Reinstalling all dependencies by deleting node_modules and yarn.lock, then running yarn install.
	•	Cleaning Yarn cache with yarn cache clean.
	•	Verifying that all modules and configuration files (e.g., tailwind.config.js) were correctly set up.

**Comment by BayBreezy** [comment]
Hello @mtzrmzia I am currently investigating this. Thanks for reporting it.

**Comment by BayBreezy** [comment]
Apparently `yarn` is behaving crazy when the modules get added to the `nuxt.config` file before they are installed.

When I moved them to the list of dependencies, it works as expected. 

Try the latest released version and let me know please. Thanks

**Comment by mtzrmzia** [comment]
> Apparently `yarn` is behaving crazy when the modules get added to the `nuxt.config` file before they are installed.
> 
> When I moved them to the list of dependencies, it works as expected.
> 
> Try the latest released version and let me know please. Thanks

@BayBreezy Thanks! Now works as expected. BTW why the componentes has `className` instead just `class`? See [button](https://github.com/BayBreezy/ui-thing/blob/66e22716083e312d80113aa1fc20cbcb9810d430/components/Ui/Button.vue#L19) component for example

**Comment by BayBreezy** [comment]
That was a copy and paste error on the button LOLOL. I will fix it soon.

Thanks for confirming that it works. I also need to update the sidebar components. Will release them later today.

**Comment by mtzrmzia** [comment]
Hi @BayBreezy Have you released the updated sidebar component? 🚀

**Comment by BayBreezy** [comment]
Not yet. I am working on it 💪. 
Will be sure to notify you when I do

**Comment by BayBreezy** [comment]
Hey @mtzrmzia ! Checkout the latest updates here https://ui-thing.behonbaker.com/getting-started/changelog#december-11-2024-more-examples-refactor

Thanks for being patient 🙂
