### ISSUE TITLE
Possible to use without Nuxt?

### ISSUE THREAD

**Issue by ianhawes** [BayBreezy/ui-thing#47]
Is it possible to use these components without Nuxt?

**Comment by BayBreezy** [comment]
Hello @ianhawes,
As is, the components are very Nuxt specific.
I think you could get them to work with [shadcn-vue](https://www.shadcn-vue.com/) in a Vue project. I haven't tried but the configuration is similar.

I am sure with a little amount of tweaking you would be able to get the components to work.

**Comment by BayBreezy** [comment]
Closing this for now. Feel free to mention me if you have any other question. Happy Coding :)
