### ISSUE TITLE
Tags Input example is incorrect

### ISSUE THREAD

**Issue by arshx86** [BayBreezy/ui-thing#48]
[Tags Input](https://ui-thing.behonbaker.com/components/tagsinput#installation) page is providing 'Tabs' example rather than actual tags input component. Probably a oversight.

![image](https://github.com/user-attachments/assets/2ec42e03-169c-4130-9bc9-03c00b3d4fb7)

**Comment by BayBreezy** [comment]
Yes. Definitely an oversight. Will fix it and push the changes soon.

Thanks for reporting
