### ISSUE TITLE
How to call the expand and collapse methods of SplitterPanel?

### ISSUE THREAD

**Issue by mirari** [BayBreezy/ui-thing#8]
I have tried to rewrite `UiSplitterPanel` like this, with `useForwardExpose`:
```
<script lang="ts" setup>
import { SplitterPanel, useForwardExpose, useForwardPropsEmits } from 'radix-vue'
import type { SplitterPanelEmits, SplitterPanelProps } from 'radix-vue'

const props = withDefaults(defineProps<SplitterPanelProps>(), {})

const emit = defineEmits<SplitterPanelEmits>()

const forwarded = useForwardPropsEmits(props, emit)

const { forwardRef } = useForwardExpose()
</script>

<template>
  <SplitterPanel
    v-slot="{ isCollapsed, isExpanded }: { isCollapsed: boolean; isExpanded: boolean }"
    v-bind="forwarded"
    :ref="forwardRef"
  >
    <slot :is-collapsed="isCollapsed" :is-expanded="isExpanded" />
  </SplitterPanel>
</template>

```
I do get the `SplitterPanel` object, but it doesn't have these two methods.
But when I try to get the `SplitterPanel` directly with a fixed ref, it is possible to see both methods.

**Comment by mirari** [comment]
@zernonia 
Thank you for your reply.
In my case, as the `ui-thing` does, the `UiSplitterPanel` is  parent component of the `SplitterPanel`.
It obviously can't forward methods from internal components.
So I tried the method `useForwardExpose` which is provided by radix-vue, but strangely, this didn't take effect either.

Here is my case:
https://stackblitz.com/edit/yklhwe-mygcdd?file=src%2FApp.vue

**Comment by BayBreezy** [comment]
@mirari , I am now dealing with th eissue you pointed out. 
What I had to do to get the ref is this

```vue
<template>
  <SplitterPanel
    v-bind="forwarded"
    ref="forwardRef"
    v-slot="{ isCollapsed, isExpanded }: { isCollapsed: boolean; isExpanded: boolean }"
  >
    <slot :isCollapsed="isCollapsed" :isExpanded="isExpanded"></slot>
  </SplitterPanel>
</template>

<script lang="ts" setup>
  import { SplitterPanel, useForwardExpose, useForwardPropsEmits } from "radix-vue";
  import type { SplitterPanelEmits, SplitterPanelProps } from "radix-vue";

  const props = withDefaults(defineProps<SplitterPanelProps>(), {});

  const forwardRef = ref<InstanceType<typeof SplitterPanel>>();
  const emit = defineEmits<
    SplitterPanelEmits & {
      ready: [value: InstanceType<typeof SplitterPanel>];
    }
  >();

  const forwarded = useForwardPropsEmits(props, emit);

  onMounted(async () => {
    await nextTick();
    emit("ready", forwardRef.value!);
  });
</script>
```

And then I set the ref like this from the parent `@ready="resizableRef = $event"`

I wish I knew why using the `useForwardExpose` does not work in this case. When I use the `useForwardExpose`, I just get back an object with the `$el` property, not the methods of the SplitterPanel.

@zernonia , this is how the `useForwardExpose` is supposed to work?
